# Generated by Django 3.2.18 on 2023-08-25 10:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(default='294f2c013f7b49c1a14748d1321b138a', max_length=64, primary_key=True, serialize=False, unique=True)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('occupation', models.CharField(max_length=50)),
                ('creators_id', models.CharField(max_length=100)),
                ('date_created', models.DateField(default=django.utils.timezone.now)),
                ('date_updated', models.DateField(auto_now=True, verbose_name='date_created')),
            ],
            options={
                'ordering': ['-date_updated'],
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.CharField(default='273f74fa889a43d69f28da73c4349a25', max_length=64, primary_key=True, serialize=False, unique=True)),
                ('creators_id', models.CharField(max_length=100)),
                ('full_name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('attenders_id', models.CharField(max_length=100)),
                ('date_created', models.DateField(default=django.utils.timezone.now)),
                ('date_updated', models.DateField(auto_now=True, verbose_name='date_created')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
            options={
                'ordering': ['-date_updated'],
            },
        ),
    ]
