# Generated by Django 3.2.18 on 2023-08-25 09:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(default='2962833bc5824a8e82348734cdc0efed', max_length=64, primary_key=True, serialize=False, unique=True)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('courses', models.CharField(max_length=100)),
                ('occupation', models.CharField(max_length=50)),
                ('creators_id', models.CharField(max_length=100)),
                ('date_created', models.DateField(default=django.utils.timezone.now)),
                ('date_updated', models.DateField(auto_now=True, verbose_name='date_created')),
            ],
            options={
                'ordering': ['-date_updated'],
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.CharField(default='f561673fd5bc409487d8f5d99f8f62c5', max_length=64, primary_key=True, serialize=False, unique=True)),
                ('creators_id', models.CharField(max_length=100)),
                ('full_name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('attenders_id', models.CharField(max_length=100)),
                ('date_created', models.DateField(default=django.utils.timezone.now)),
                ('date_updated', models.DateField(auto_now=True, verbose_name='date_created')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
            options={
                'ordering': ['-date_updated'],
            },
        ),
    ]
