# Generated by Django 3.2.18 on 2023-08-25 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='id',
            field=models.CharField(default='728e18b80ab14e8c9d263108f220cb29', max_length=64, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(default='fc66580fe72b4dfc85186e71def68507', max_length=64, primary_key=True, serialize=False, unique=True),
        ),
    ]
