# Generated by Django 3.2.18 on 2023-08-25 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20230825_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='id',
            field=models.CharField(default='c7433c65791a43648d60eaa318c0fe5d', max_length=64, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='courses',
            field=models.CharField(default='course', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(default='2e3aca5d0fad4e91bfcdf901b163594f', max_length=64, primary_key=True, serialize=False, unique=True),
        ),
    ]
