# Generated by Django 3.2.18 on 2023-08-25 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20230825_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='courses',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=15, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='id',
            field=models.CharField(default='77c4e4eb11c543abb481d7c25d2a5f75', max_length=64, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, unique=True),
        ),
    ]
