# Generated by Django 3.2.18 on 2023-08-25 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20230825_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='id',
            field=models.CharField(default='6295cd9ac4c14f4282700faadc811eb8', max_length=64, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(default='ed4a59a38d4a469e9798d6f42e62fd30', max_length=64, primary_key=True, serialize=False, unique=True),
        ),
    ]
