# Generated by Django 3.2.18 on 2023-08-25 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20230825_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='id',
            field=models.CharField(default='70a671322a694990b65fa67697adb158', max_length=64, primary_key=True, serialize=False, unique=True),
        ),
    ]
