# Generated by Django 3.2.18 on 2023-08-25 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_attendance_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='id',
            field=models.CharField(default='e5d6e0e59f674d458344b26385465f75', max_length=64, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='courses',
            field=models.CharField(default=9, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(default=90, max_length=15),
            preserve_default=False,
        ),
    ]
