# Generated by Django 3.2.18 on 2023-08-27 18:23

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20230825_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='id',
            field=models.CharField(default=api.models.generate_id, max_length=64, primary_key=True, serialize=False, unique=True),
        ),
    ]
