# Generated by Django 3.2.18 on 2024-06-25 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20230827_1923'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='title',
        ),
    ]
