# Generated by Django 3.2.18 on 2024-06-26 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20240625_1704'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='creators_id',
        ),
        migrations.AlterField(
            model_name='attendance',
            name='creators_id',
            field=models.CharField(max_length=10),
        ),
    ]
