# Generated by Django 3.2.18 on 2024-07-03 05:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20240626_0018'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.IntegerField(default=0, max_length=10, primary_key=True, serialize=False, unique=True)),
                ('course_code', models.CharField(max_length=100)),
                ('date_created', models.DateField(default=django.utils.timezone.now)),
                ('date_updated', models.DateField(auto_now=True, verbose_name='date_created')),
            ],
            options={
                'ordering': ['-date_updated'],
            },
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='subject',
        ),
        migrations.AddField(
            model_name='attendance',
            name='course',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='api.course'),
            preserve_default=False,
        ),
    ]
