# Generated by Django 3.2.18 on 2024-07-03 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20240703_0540'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='creators_id',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='user',
        ),
    ]
