# Generated by Django 3.2.18 on 2024-07-20 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAuth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.CharField(default='c7bb69ec8f36423abebd4fe9cb293bc3', max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='level',
            field=models.IntegerField(),
        ),
    ]
