# Generated by Django 3.2.18 on 2024-07-20 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAuth', '0002_auto_20240720_0426'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentprofile',
            old_name='updated_date',
            new_name='date_updated',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.CharField(default='f667f3e8b7b1413099a8d16e390f1ded', max_length=100, primary_key=True, serialize=False),
        ),
    ]
