# Generated by Django 3.2.18 on 2024-07-20 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAuth', '0003_auto_20240720_0436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.CharField(default='b63f8eb00f1e4eb18315aa5f15d70376', max_length=100, primary_key=True, serialize=False),
        ),
    ]
