# Generated by Django 3.2.18 on 2024-08-18 10:56

import UserAuth.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAuth', '0004_alter_customuser_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.CharField(default=UserAuth.utils.generate_id, max_length=100, primary_key=True, serialize=False),
        ),
    ]
